# Build config for travis-ci.org
language: node_js
node_js:
  - 0.10
install:
  - "wget http://dl.google.com/closure-compiler/compiler-latest.zip"
  - "unzip -n compiler-latest.zip"
script:
  # TODO: Enable checkTypes after adding more types to externs.js
  - "java -jar compiler.jar --warning_level=VERBOSE *.js --jscomp_off=checkTypes
    --externs=externs/externs.js --externs=externs/core.js --externs=externs/process.js
    --externs=externs/underscore-1.5.1.js  > /dev/null"
